#!/bin/bash

####
#### Victor's script for extracting an rpm
####

if [ $# -lt 2 ] ; then
    echo "Usage: $0 rpm"
    exit 1
fi

rpm=$1

if [ ! -f "$rpm" ] ; then
    echo "Could not find rpm <<$rpm>>"
    exit 1;
fi

pm2cpio $rpm | cpio -i --make-directories
