#!/bin/sh

  RPM_SOURCE_DIR="/admin/build/rpms/SOURCES"
  RPM_BUILD_DIR="/admin/build/rpms/BUILD"
  RPM_OPT_FLAGS="-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic"
  RPM_LD_FLAGS="-Wl,-z,relro "
  RPM_ARCH="x86_64"
  RPM_OS="linux"
  export RPM_SOURCE_DIR RPM_BUILD_DIR RPM_OPT_FLAGS RPM_LD_FLAGS RPM_ARCH RPM_OS
  RPM_DOC_DIR="/usr/share/doc"
  export RPM_DOC_DIR
  RPM_PACKAGE_NAME="tacc-gamess-intel18-impi18_0"
  RPM_PACKAGE_VERSION="2018.02.14"
  RPM_PACKAGE_RELEASE="1.el7.centos"
  export RPM_PACKAGE_NAME RPM_PACKAGE_VERSION RPM_PACKAGE_RELEASE
  LANG=C
  export LANG
  unset CDPATH DISPLAY ||:
  RPM_BUILD_ROOT="/root/rpmbuild/BUILDROOT/tacc-gamess-intel18-impi18_0-2018.02.14-1.el7.centos.x86_64"
  export RPM_BUILD_ROOT
  
  PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:/usr/lib64/pkgconfig:/usr/share/pkgconfig"
  export PKG_CONFIG_PATH
  
  set -x
  umask 022
  cd "/admin/build/rpms/BUILD"
    [ "$RPM_BUILD_ROOT" != "/" ] && rm -rf "${RPM_BUILD_ROOT}"
    mkdir -p `dirname "$RPM_BUILD_ROOT"`
    mkdir "$RPM_BUILD_ROOT"

cd 'gamess-2018.02.14'


  rm   -rf $RPM_BUILD_ROOT//opt/apps/intel18/impi18_0/gamess/2018.02.14 # Delete the package installation directory.
  mkdir -p $RPM_BUILD_ROOT//opt/apps/intel18/impi18_0/gamess/2018.02.14
  mkdir -p $RPM_BUILD_ROOT//opt/apps/intel18/impi18_0/gamess/2018.02.14/auxdata
  mkdir -p $RPM_BUILD_ROOT//opt/apps/intel18/impi18_0/gamess/2018.02.14/doc
  


  echo "TACC_OPT -xCORE-AVX2 -axMIC-AVX512,CORE-AVX512"
                              # This puts everything in INSTALL_DIR 
                              # into the RPM_BUILD_ROOT/INSTALL_DIR dir

                              # we are in %{_topdir}/BUILD = /admin/build/rpms
                              # we are in %{_builddir}/%{pkg_basename}-%{version}   where things are made

  #                       #Move files to rpm build directories
  
  cp -p         gms-files.csh    $RPM_BUILD_ROOT//opt/apps/intel18/impi18_0/gamess/2018.02.14
  cp gamess.*                    $RPM_BUILD_ROOT//opt/apps/intel18/impi18_0/gamess/2018.02.14
  cp -p TACC_FILES/rungms_sp2 $RPM_BUILD_ROOT//opt/apps/intel18/impi18_0/gamess/2018.02.14/rungms

  cp -pr              auxdata    $RPM_BUILD_ROOT//opt/apps/intel18/impi18_0/gamess/2018.02.14
  rm -rf                         $RPM_BUILD_ROOT//opt/apps/intel18/impi18_0/gamess/2018.02.14/auxdata/QUANPOL/RXNFLD3840.DAT

  cp -pr                tools    $RPM_BUILD_ROOT//opt/apps/intel18/impi18_0/gamess/2018.02.14

  cp                    *.DOC    $RPM_BUILD_ROOT//opt/apps/intel18/impi18_0/gamess/2018.02.14/doc

  chmod a+rX                     $RPM_BUILD_ROOT//opt/apps/intel18/impi18_0/gamess/2018.02.14
  chmod a+rx                     $RPM_BUILD_ROOT//opt/apps/intel18/impi18_0/gamess/2018.02.14/gms-files.csh
  chmod a+rx                     $RPM_BUILD_ROOT//opt/apps/intel18/impi18_0/gamess/2018.02.14/gamess.*
  chmod a+rx                     $RPM_BUILD_ROOT//opt/apps/intel18/impi18_0/gamess/2018.02.14/rungms

 # Extend user permissions to other and group, but remove w on other
  chmod -R g=u                   $RPM_BUILD_ROOT//opt/apps/intel18/impi18_0/gamess/2018.02.14/auxdata
  chmod -R o=u                   $RPM_BUILD_ROOT//opt/apps/intel18/impi18_0/gamess/2018.02.14/auxdata
  chmod -R o-w                   $RPM_BUILD_ROOT//opt/apps/intel18/impi18_0/gamess/2018.02.14/auxdata

 # Extend user permissions to other and group, but remove w on other
  chmod -R g=u                   $RPM_BUILD_ROOT//opt/apps/intel18/impi18_0/gamess/2018.02.14/tools
  chmod -R o=u                   $RPM_BUILD_ROOT//opt/apps/intel18/impi18_0/gamess/2018.02.14/tools
  chmod -R o-w                   $RPM_BUILD_ROOT//opt/apps/intel18/impi18_0/gamess/2018.02.14/tools

  chmod a+rx                     $RPM_BUILD_ROOT//opt/apps/intel18/impi18_0/gamess/2018.02.14/doc
  chmod a+r                      $RPM_BUILD_ROOT//opt/apps/intel18/impi18_0/gamess/2018.02.14/doc/*


 #cp -r tests $RPM_BUILD_ROOT//opt/apps/intel18/impi18_0/gamess/2018.02.14
                
  





    
    /usr/lib/rpm/check-buildroot
    
    /usr/lib/rpm/redhat/brp-compress 
    
    /usr/lib/rpm/redhat/brp-strip /usr/bin/strip 
    /usr/lib/rpm/redhat/brp-strip-comment-note /usr/bin/strip /usr/bin/objdump 
     
    /usr/lib/rpm/redhat/brp-strip-static-archive /usr/bin/strip 
    /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1 
    /usr/lib/rpm/redhat/brp-python-hardlink 
    /usr/lib/rpm/redhat/brp-java-repack-jars 

