#!/usr/bin/env bash
#
# W. Cyrus Proctor
# 2015-10-25

export log=coverage.log

echo `date` > ${log}
for VERBOSE in `seq 0 2`; do
  printf '=%.0s' {1..80}           2>&1 | tee -a ${log}
  echo                             2>&1 | tee -a ${log}
  printf '=%.0s' {1..80}           2>&1 | tee -a ${log}
  echo                             2>&1 | tee -a ${log}
  printf '=%.0s' {1..80}           2>&1 | tee -a ${log}
  echo                             2>&1 | tee -a ${log}
  echo "VERBOSE set to ${VERBOSE}" 2>&1 | tee -a ${log}
  printf '=%.0s' {1..80}           2>&1 | tee -a ${log}
  echo                             2>&1 | tee -a ${log}
  printf '=%.0s' {1..80}           2>&1 | tee -a ${log}
  echo                             2>&1 | tee -a ${log}
  printf '=%.0s' {1..80}           2>&1 | tee -a ${log}
  echo                             2>&1 | tee -a ${log}
  for run in `seq 1 37`; do
    printf '=%.0s' {1..80}         2>&1 | tee -a ${log}
    echo                           2>&1 | tee -a ${log}
    ./coverage ${run}              2>&1 | tee -a ${log}
  done
done
